### ISSUE TITLE
Panic: invalid state: no nodes have remaining edges

### ISSUE THREAD

**Issue by romankydybets** [helmfile/helmfile#1062]
### Operating system

MacOs 13.4.1 (c) 

### Helmfile Version

v0.155.0

### Helm Version

version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}

### Bug description

when i execute 
```
helmfile lint -e prodlike --file services.yaml
```
	
versions.yaml
```
versions:
  dbms:
    suffix: RC
    version: 2.170.0
  rc-test-service:
    suffix: RC
    version: 1.11.1
  game-test-manager:
    suffix: RC
    version: 1.46.0
```

if i commented out `rc-test-service` everything went ok
if i commented out `dbms` it also went ok

### Example helmfile.yaml

*

### Error message you've seen (if any)

```
Fetching RC/game-test-manager
Fetching RC/dbms
Fetching RC/rc-test-service
panic: invalid state: no nodes have remaining edges: nodes=[rc-test-service/rc-test-service]

goroutine 39 [running]:
github.com/variantdev/dag/pkg/dag.(*DAG).Sort(0x140001177c0, {0x14000724f20, 0x1, 0x14001764360?})
	github.com/variantdev/dag@v1.1.0/pkg/dag/dag.go:474 +0x15f8
github.com/variantdev/dag/pkg/dag.(*DAG).Plan(...)
	github.com/variantdev/dag@v1.1.0/pkg/dag/dag.go:198
github.com/helmfile/helmfile/pkg/state.GroupReleasesByDependency({0x1400099a000, 0x3, 0x4?}, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x1, {0x14000994000, ...}})
	github.com/helmfile/helmfile/pkg/state/state_run.go:164 +0x77c
github.com/helmfile/helmfile/pkg/state.SortedReleaseGroups({0x1400099a000?, 0x0?, 0x0?}, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x1, {0x14000994000, ...}})
	github.com/helmfile/helmfile/pkg/state/state_run.go:118 +0x60
github.com/helmfile/helmfile/pkg/state.(*HelmState).PlanReleases(0x140008e2800?, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x1, {0x14000994000, 0x3, 0x4}})
	github.com/helmfile/helmfile/pkg/state/state_run.go:107 +0x70
github.com/helmfile/helmfile/pkg/app.(*App).withNeeds(0x140008e2800, 0x140003f0990, {0x12f1bb2b8, 0x140006a6430}, 0x0, 0x14000726f80)
	github.com/helmfile/helmfile/pkg/app/app.go:1930 +0x154
github.com/helmfile/helmfile/pkg/app.(*App).lint(0x14000726ff8?, 0x140003f0990, {0x105277e20?, 0x140006a6430})
	github.com/helmfile/helmfile/pkg/app/app.go:1622 +0x8c
github.com/helmfile/helmfile/pkg/app.(*App).Lint.func1.1()
	github.com/helmfile/helmfile/pkg/app/app.go:330 +0x44
github.com/helmfile/helmfile/pkg/app.(*Run).withPreparedCharts(0x140003f0990, {0x10441a04d, 0x4}, {0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/run.go:100 +0x418
github.com/helmfile/helmfile/pkg/app.(*App).Lint.func1(0x140003f0990)
	github.com/helmfile/helmfile/pkg/app/app.go:322 +0x17c
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState.func1(0x1400158fb80?)
	github.com/helmfile/helmfile/pkg/app/app.go:967 +0xc0
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func2(0x1400158fb80)
	github.com/helmfile/helmfile/pkg/app/app.go:1089 +0x70
github.com/helmfile/helmfile/pkg/app.(*App).visitStates.func1({0x16d8db671, 0xd}, {0x140008b05c0, 0x38})
	github.com/helmfile/helmfile/pkg/app/app.go:911 +0x538
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles.func1()
	github.com/helmfile/helmfile/pkg/app/app.go:737 +0x34
github.com/helmfile/helmfile/pkg/app.(*App).within(0x140008e2800, {0x140008b05c0, 0x38}, 0x140000909e8)
	github.com/helmfile/helmfile/pkg/app/app.go:699 +0x1c8
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles(0x140008e2800, {0x16d8db671?, 0x28?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/app.go:736 +0x2bc
github.com/helmfile/helmfile/pkg/app.(*App).visitStates(0x140008e2800, {0x16d8db671?, 0x0?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/app.go:815 +0xe0
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0x140008e2800, {0x16d8db671, 0xd}, 0x14000090c78, 0x0, {0x0, 0x0, 0x140008aab70?})
	github.com/helmfile/helmfile/pkg/app/app.go:1092 +0x3cc
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState(0x140008e2800, 0x14000090cf0, 0xb0?, {0x0, 0x0, 0x0})
	github.com/helmfile/helmfile/pkg/app/app.go:960 +0x8c
github.com/helmfile/helmfile/pkg/app.(*App).Lint(0x140008e2800, {0x105277e20, 0x140006a6430})
	github.com/helmfile/helmfile/pkg/app/app.go:318 +0x8c
github.com/helmfile/helmfile/cmd.NewLintCmd.func1(0x140008be600?, {0x104419f31?, 0x4?, 0x4?})
	github.com/helmfile/helmfile/cmd/lint.go:29 +0xcc
github.com/spf13/cobra.(*Command).execute(0x140008be600, {0x140008a7ec0, 0x4, 0x4})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140008ac000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x140004be000?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main.func1()
	github.com/helmfile/helmfile/main.go:29 +0x64
created by main.main
	github.com/helmfile/helmfile/main.go:21 +0xcc
```

### Steps to reproduce

*

### Working Helmfile Version

v0.155.0

**Comment by romankydybets** [comment]
it was due to duplicates entry in release.yaml in `need` section
