### ISSUE TITLE
feat: enhancing error message

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#1220]
### Discussed in https://github.com/helmfile/helmfile/discussions/1218

<div type='discussions-op-text'>

<sup>Originally posted by **jjangga0214** December 13, 2023</sup>
For instance,

```yaml
  - name: foo
    chart: ./foo
    condition: fooo.enabled # <-- typo. It should be `foo.enabled`
```

When there's a typo in `condition`, the error message is like this.
It does not show the line number nor contain human-readable information. 
The only helpful message is `github.com/helmfile/helmfile/pkg/state.ConditionEnabled`, which is a too weak hint.

I hope this to be enhanced.

```bash
goroutine 52 [running]:
github.com/helmfile/helmfile/pkg/state.ConditionEnabled({{0x1400096ca70, 0xd}, {0x14000010dd0, 0xb}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...)
	github.com/helmfile/helmfile/pkg/state/state.go:2231 +0x238
github.com/helmfile/helmfile/pkg/state.markExcludedReleases({0x140004d0a80?, 0x1e, 0x22}, {0x1052da8e0?, 0x0, 0x102062b64?}, 0x0?, 0x0?, 0x0)
	github.com/helmfile/helmfile/pkg/state/state.go:2198 +0x43c
github.com/helmfile/helmfile/pkg/state.(*HelmState).SelectReleases(0x0?, 0xe0?)
	github.com/helmfile/helmfile/pkg/state/state.go:2156 +0x50
github.com/helmfile/helmfile/pkg/state.(*HelmState).GetSelectedReleases(0x140009a9578?, 0xc0?)
	github.com/helmfile/helmfile/pkg/state/state.go:2276 +0x24
github.com/helmfile/helmfile/pkg/app.(*App).getSelectedReleases(0x14000924600, 0x14000cc40f0, 0xc0?)
	github.com/helmfile/helmfile/pkg/app/app.go:1247 +0x44
github.com/helmfile/helmfile/pkg/app.(*App).apply(0x14000924600, 0x14000cc40f0, {0x103b998c8, 0x14000599450})
	github.com/helmfile/helmfile/pkg/app/app.go:1325 +0xb8
github.com/helmfile/helmfile/pkg/app.(*App).Apply.func1.1()
	github.com/helmfile/helmfile/pkg/app/app.go:423 +0x4c
github.com/helmfile/helmfile/pkg/app.(*Run).withPreparedCharts(0x14000cc40f0, {0x102c5e0db, 0x5}, {0x0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x14000142ea0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/run.go:100 +0x3f8
github.com/helmfile/helmfile/pkg/app.(*App).Apply.func1(0x14000cc40f0)
	github.com/helmfile/helmfile/pkg/app/app.go:412 +0x228
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState.func1(0x140008d8dc0?)
	github.com/helmfile/helmfile/pkg/app/app.go:967 +0xbc
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func2(0x140008d8dc0)
	github.com/helmfile/helmfile/pkg/app/app.go:1089 +0x64
github.com/helmfile/helmfile/pkg/app.(*App).visitStates.func1({0x102c6eda4, 0xd}, {0x1400079a860, 0x1a})
	github.com/helmfile/helmfile/pkg/app/app.go:911 +0x534
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles.func1()
	github.com/helmfile/helmfile/pkg/app/app.go:737 +0x38
github.com/helmfile/helmfile/pkg/app.(*App).within(0x14000924600, {0x1400079a860, 0x1a}, 0x1400092d9b8)
	github.com/helmfile/helmfile/pkg/app/app.go:699 +0x1c8
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles(0x14000924600, {0x0?, 0x24?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/app.go:736 +0x2b8
github.com/helmfile/helmfile/pkg/app.(*App).visitStates(0x14000924600, {0x0?, 0x0?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
	github.com/helmfile/helmfile/pkg/app/app.go:815 +0xe0
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0x14000924600, {0x0, 0x0}, 0x140000a9c38, 0x0, {0x1400009a168, 0x1, 0x0?})
	github.com/helmfile/helmfile/pkg/app/app.go:1092 +0x35c
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState(0x14000924600, 0x140000a9ce8, 0x0?, {0x1400009a168, 0x1, 0x1})
	github.com/helmfile/helmfile/pkg/app/app.go:960 +0x8c
github.com/helmfile/helmfile/pkg/app.(*App).Apply(0x14000924600, {0x103b998c8, 0x14000599450})
	github.com/helmfile/helmfile/pkg/app/app.go:409 +0x13c
github.com/helmfile/helmfile/cmd.NewApplyCmd.func1(0x1400063c500?, {0x102c5d2f1?, 0x4?, 0x102c5d3b9?})
	github.com/helmfile/helmfile/cmd/apply.go:31 +0x10c
github.com/spf13/cobra.(*Command).execute(0x140007a9200, {0x1400099b050, 0x3, 0x3})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140007a8c00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(0x140005742d0?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main.func1()
	github.com/helmfile/helmfile/main.go:29 +0x64
created by main.main in goroutine 1
	github.com/helmfile/helmfile/main.go:21 +0xc8
 ELIFECYCLE  Command failed with exit code 2.
```</div>

**Comment by yxxhero** [comment]
@jjangga0214 please  show your values.

**Comment by yxxhero** [comment]
@jjangga0214 fixed. thanks for your feedback.

**Comment by yxxhero** [comment]
@jjangga0214 could you post your values?
